name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner label here if needed

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Adjust the .NET version as per your project's requirement

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./WebApp  # Set the working directory to your project's root

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./WebApp  # Set the working directory to your project's root
