name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Specifies that this job runs on a self-hosted runner

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Specify the .NET version your project uses

    - name: Restore dependencies
      run: dotnet restore ./WebApp/WebApp.csproj  # Adjust the path to your .csproj file

    - name: Build
      run: dotnet build --no-restore --configuration Release ./WebApp/WebApp.csproj  # Adjust the path to your .csproj file
